- name: Copy atifact zip file
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: extract zip file
  become: true
  shell:
    "mkdir project && tar -xf artifact.tar.gz -C project"

- name: putting env file
  become: true
  shell:
    "cd project && sudo mv .env.sample .env"

- name: install packages and run the server
  become: true
  shell:
    "cd project && sudo npm install && sudo pm2 start npm -- start"