- name: Copy atifact zip file
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: extract zip file
  become: true
  shell:
    "tar -xf artifact.tar.gz"

- name: install packages and run the server
  become: true
  shell:
    "npm install &&\
     pm2 stop default &&\
     pm2 start npm -- start"
